import { StyleSheet } from 'react-native';
import { colors } from "./colors";

export const forYouStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 42,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: colors.textPrimary,
  },
  searchInputLarge: {
    flex: 1,
    fontSize: 16,
    color: colors.textPrimary,
    paddingVertical: 2,
  },
  cameraButton: {
    padding: 4,
  },
  searchButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  filterButton: {
    padding: 8,
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
    marginLeft: 8,
  },
  aiSearchButton: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: '#f0f8ff',
    marginLeft: 6,
    borderWidth: 1,
    borderColor: '#007AFF',
  },
  clearButton: {
    padding: 4,
    marginLeft: 6,
  },
  searchButtonText: {
    color: colors.textLight,
    fontSize: 14,
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  bannerContainer: {
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  banner: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 20,
    height: 140,
    justifyContent: 'center',
  },
  bannerText: {
    color: colors.textLight,
    fontSize: 32,
    fontWeight: 'bold',
  },
  bannerSubtext: {
    color: colors.textLight,
    fontSize: 18,
    fontWeight: '400',
    marginTop: 4,
  },
  quickAccessContainer: {
    backgroundColor: colors.surface,
    paddingVertical: 16,
    marginTop: 12,
  },
  quickAccessItem: {
    alignItems: 'center',
    marginHorizontal: 10,
    width: 78,
    paddingHorizontal: 2,
  },
  quickAccessIcon: {
    width: 60,
    height: 60,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  quickAccessLabel: {
    fontSize: 11,
    color: colors.textPrimary,
    textAlign: 'center',
    paddingHorizontal: 2,
  },
  voucherSection: {
    backgroundColor: colors.surface,
    padding: 16,
    marginTop: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginLeft: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  moreLink: {
    fontSize: 12,
    color: colors.primary,
  },
  voucherCards: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  voucherCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 8,
    padding: 12,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  voucherDiscount: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  voucherSubtitle: {
    fontSize: 12,
    color: colors.info,
    marginTop: 4,
  },
  collectAllButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  collectAllText: {
    color: colors.textLight,
    fontSize: 14,
    fontWeight: '600',
  },
  flashSaleSection: {
    backgroundColor: colors.surface,
    padding: 16,
    marginTop: 12,
  },
  flashSaleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  flashSaleTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  countdown: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  countdownBox: {
    backgroundColor: colors.error,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  countdownText: {
    color: colors.textLight,
    fontSize: 12,
    fontWeight: 'bold',
  },
  countdownSeparator: {
    color: colors.error,
    fontSize: 12,
    fontWeight: 'bold',
    marginHorizontal: 2,
  },
  productScroll: {
    marginTop: 8,
  },
  productCard: {
    width: 140,
    marginRight: 12,
    backgroundColor: colors.surface,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  productImageContainer: {
    position: 'relative',
    width: '100%',
    height: 140,
    backgroundColor: colors.background,
  },
  productImage: {
    width: 140,
    height: 140,
    resizeMode: 'contain',
  },
  productLabel: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
  },
  productLabelText: {
    color: colors.textLight,
    fontSize: 9,
    fontWeight: 'bold',
  },
  soldBadge: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingVertical: 4,
    alignItems: 'center',
  },
  soldText: {
    color: colors.textLight,
    fontSize: 11,
    fontWeight: '600',
  },
  productInfo: {
    padding: 8,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  productPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
  },
  hotBadge: {
    backgroundColor: colors.warning,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  hotBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  discountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  originalPrice: {
    fontSize: 12,
    color: colors.textMuted,
    textDecorationLine: 'line-through',
    marginRight: 6,
  },
  discountBadge: {
    fontSize: 11,
    color: colors.error,
    fontWeight: '600',
  },
  dailyChoiceSection: {
    backgroundColor: colors.surface,
    padding: 16,
    marginTop: 12,
    marginBottom: 60,
  },
  // Skeleton loading styles
  skeletonImage: {
    width: '100%',
    height: 140,
    backgroundColor: colors.background,
    borderRadius: 0,
  },
  skeletonBadge: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 24,
    backgroundColor: colors.background,
  },
  skeletonPrice: {
    width: 60,
    height: 16,
    backgroundColor: colors.background,
    borderRadius: 4,
    marginBottom: 4,
  },
  skeletonOriginalPrice: {
    width: 80,
    height: 12,
    backgroundColor: colors.background,
    borderRadius: 4,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    width: '80%',
    maxWidth: 300,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 8,
    backgroundColor: '#f8f8f8',
    marginBottom: 10,
  },
  filterOptionActive: {
    backgroundColor: colors.primary,
  },
  filterOptionText: {
    marginLeft: 12,
    fontSize: 16,
    color: '#666',
  },
  filterOptionTextActive: {
    color: 'white',
  },
});